version: "3"
services:
        web:
                image: python:latest
                working_dir: /app
                container_name: Hyphen
                command: bash -c "pip install -r requirements.txt && python3 manage.py runserver 0.0.0.0:8000"
                volumes:
                        - "./code/:/app/"
                ports:
                        - 80:8000

