
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:    
      - uses: actions/checkout@v2
      - name: pull from github
        working-directory: /var/www/HelloWorld/sayches
        run: sudo GIT_SSH_COMMAND="ssh -i ~/root/.ssh/runner" git pull
      - name: start docker-compose file
        working-directory: /var/www/HelloWorld/sayches
        run: sudo docker-compose -f docker-compose.yaml up -d 
