
name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:    
      - uses: actions/checkout@v2
      - name: pull from github
        run: git pull 
      - name: start docker-compose file
        run: docker-compose -f docker-compose.yaml up -d 
